INSERT INTO PM_USER_DATA (USER_ID, FULL_NAME, PASSWORD, STATUS_CD)
VALUES('i2b2', 'i2b2 Admin', '9117d59a69dc49807671a51f10ab7f', 'A');
INSERT INTO PM_USER_DATA (USER_ID, FULL_NAME, PASSWORD, STATUS_CD)
VALUES('OBFSC_SERVICE_ACCOUNT', 'OBFSC_SERVICE_ACCOUNT', '9117d59a69dc49807671a51f10ab7f', 'A');
INSERT INTO PM_USER_DATA (USER_ID, FULL_NAME, PASSWORD, STATUS_CD)
VALUES('AGG_SERVICE_ACCOUNT', 'AGG_SERVICE_ACCOUNT', '9117d59a69dc49807671a51f10ab7f', 'A');
INSERT INTO PM_HIVE_DATA (DOMAIN_ID, HELPURL, DOMAIN_NAME, ENVIRONMENT_CD, ACTIVE, STATUS_CD)
VALUES('i2b2', 'http://www.i2b2.org', 'i2b2demo', 'DEVELOPMENT', 1, 'A');
INSERT INTO PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, STATUS_CD)
VALUES('@', 'i2b2', 'ADMIN', 'A');
INSERT INTO PM_ROLE_REQUIREMENT(TABLE_CD, COLUMN_CD, READ_HIVEMGMT_CD, WRITE_HIVEMGMT_CD, NAME_CHAR, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES('PM_HIVE_DATA', '@', '@', 'ADMIN', NULL, NULL, NULL, NULL, 'A');
INSERT INTO PM_ROLE_REQUIREMENT(TABLE_CD, COLUMN_CD, READ_HIVEMGMT_CD, WRITE_HIVEMGMT_CD, NAME_CHAR, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES('PM_HIVE_PARAMS', '@', '@', 'ADMIN', NULL, NULL, NULL, NULL, 'A');
INSERT INTO PM_ROLE_REQUIREMENT(TABLE_CD, COLUMN_CD, READ_HIVEMGMT_CD, WRITE_HIVEMGMT_CD, NAME_CHAR, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES('PM_PROJECT_DATA', '@', '@', 'MANAGER', NULL, NULL, NULL, NULL, 'A');
INSERT INTO PM_ROLE_REQUIREMENT(TABLE_CD, COLUMN_CD, READ_HIVEMGMT_CD, WRITE_HIVEMGMT_CD, NAME_CHAR, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES('PM_PROJECT_USER_ROLES', '@', '@', 'MANAGER', NULL, NULL, NULL, NULL, 'A');
INSERT INTO PM_ROLE_REQUIREMENT(TABLE_CD, COLUMN_CD, READ_HIVEMGMT_CD, WRITE_HIVEMGMT_CD, NAME_CHAR, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES('PM_USER_DATA', '@', '@', 'ADMIN', NULL, NULL, NULL, NULL, 'A');
INSERT INTO PM_ROLE_REQUIREMENT(TABLE_CD, COLUMN_CD, READ_HIVEMGMT_CD, WRITE_HIVEMGMT_CD, NAME_CHAR, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES('PM_PROJECT_PARAMS', '@', '@', 'MANAGER', NULL, NULL, NULL, NULL, 'A');
INSERT INTO PM_ROLE_REQUIREMENT(TABLE_CD, COLUMN_CD, READ_HIVEMGMT_CD, WRITE_HIVEMGMT_CD, NAME_CHAR, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES('PM_PROJECT_USER_PARAMS', '@', '@', 'MANAGER', NULL, NULL, NULL, NULL, 'A');
INSERT INTO PM_ROLE_REQUIREMENT(TABLE_CD, COLUMN_CD, READ_HIVEMGMT_CD, WRITE_HIVEMGMT_CD, NAME_CHAR, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES('PM_USER_PARAMS', '@', '@', 'ADMIN', NULL, NULL, NULL, NULL, 'A');
INSERT INTO PM_ROLE_REQUIREMENT(TABLE_CD, COLUMN_CD, READ_HIVEMGMT_CD, WRITE_HIVEMGMT_CD, NAME_CHAR, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES('PM_CELL_DATA', '@', '@', 'MANAGER', NULL, NULL, NULL, NULL, 'A');
INSERT INTO PM_ROLE_REQUIREMENT(TABLE_CD, COLUMN_CD, READ_HIVEMGMT_CD, WRITE_HIVEMGMT_CD, NAME_CHAR, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES('PM_CELL_PARAMS', '@', '@', 'MANAGER', NULL, NULL, NULL, NULL, 'A');
INSERT INTO PM_ROLE_REQUIREMENT(TABLE_CD, COLUMN_CD, READ_HIVEMGMT_CD, WRITE_HIVEMGMT_CD, NAME_CHAR, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
  VALUES('PM_GLOBAL_PARAMS', '@', '@', 'ADMIN', NULL, NULL, NULL, NULL, 'A');	