DROP TABLE PM_CELL_DATA;
DROP TABLE PM_CELL_PARAMS ;
DROP TABLE PM_GLOBAL_PARAMS ;
DROP TABLE PM_HIVE_DATA ;
DROP TABLE PM_HIVE_PARAMS ;
DROP TABLE PM_PROJECT_DATA ;
DROP TABLE PM_PROJECT_PARAMS ;
DROP TABLE PM_PROJECT_USER_PARAMS ;
DROP TABLE PM_PROJECT_USER_ROLES ;
DROP TABLE PM_USER_DATA ;
DROP TABLE PM_USER_PARAMS ;
DROP TABLE PM_ROLE_REQUIREMENT ;
DROP TABLE PM_USER_SESSION ;

	