DROP TABLE Encounter_Mapping ;
DROP TABLE Patient_Mapping ;
DROP TABLE concept_dimension ;
DROP TABLE Patient_Dimension ;
DROP TABLE Provider_Dimension ;
DROP TABLE Visit_Dimension ;
DROP TABLE Observation_Fact ;
DROP TABLE CODE_LOOKUP ; 

--

DROP TABLE ARCHIVE_OBSERVATION_FACT ;

DROP table DATAMART_REPORT ;
DROP TABLE UPLOAD_STATUS ;

DROP TABLE SOURCE_MASTER ;
DROP TABLE SET_UPLOAD_STATUS ;
DROP TABLE SET_TYPE ;

--

drop TABLE QT_PATIENT_SET_COLLECTION ;
drop TABLE QT_PATIENT_ENC_COLLECTION ;
drop TABLE QT_XML_RESULT ;

drop TABLE QT_QUERY_RESULT_INSTANCE ;
drop TABLE QT_QUERY_RESULT_TYPE ;


drop TABLE QT_QUERY_INSTANCE ;
drop TABLE QT_QUERY_STATUS_TYPE ;

drop TABLE QT_QUERY_MASTER ;

drop TABLE QT_ANALYSIS_PLUGIN;

drop TABLE QT_ANALYSIS_PLUGIN_RESULT_TYPE ;
drop table QT_PRIVILEGE ;
drop table QT_BREAKDOWN_PATH ;
    
drop TABLE QT_PDO_QUERY_MASTER ;




