/*========================================
  Postgres SQL pm inserts for a project 
  
  Substitutions required for:
  	<PROJECT_ID>
  ========================================*/ 

set schema 'i2b2pm';

INSERT INTO i2b2pm.PM_HIVE_DATA(domain_id, helpurl, domain_name, environment_cd, active, change_date, entry_date, changeby_char, status_cd)
(
   SELECT 'BRISSKIT', 'www.brisskit.le.ac.uk', 'BRISSKIT', 'DEVELOPMENT', 1, now(), now(), '', 'A' 
   WHERE NOT EXISTS( SELECT * FROM I2B2PM.PM_HIVE_DATA WHERE DOMAIN_ID = 'BRISSKIT' ) 
) ;

INSERT INTO i2b2pm.PM_PROJECT_DATA (PROJECT_ID, PROJECT_NAME, PROJECT_WIKI, PROJECT_KEY, PROJECT_PATH, PROJECT_DESCRIPTION, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES ('<PROJECT_ID>', '<PROJECT_ID>', 'http://www.i2b2.org', null, '/<PROJECT_ID>', null, now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES ('<PROJECT_ID>', 'demo', 'DATA_OBFSC', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES ('<PROJECT_ID>', 'demo', 'USER', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<PROJECT_ID>','AGG_SERVICE_ACCOUNT','DATA_AGG', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<PROJECT_ID>','AGG_SERVICE_ACCOUNT','DATA_OBFSC', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<PROJECT_ID>','AGG_SERVICE_ACCOUNT','MANAGER', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<PROJECT_ID>','AGG_SERVICE_ACCOUNT','USER', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<PROJECT_ID>','demo','DATA_AGG', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<PROJECT_ID>','demo','ADMIN', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<PROJECT_ID>','demo','DATA_LDS', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<PROJECT_ID>','demo','DATA_PROT', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<PROJECT_ID>','demo','DATA_DEID', now(), now(), null, 'A');

INSERT INTO i2b2pm.PM_PROJECT_USER_ROLES (PROJECT_ID, USER_ID, USER_ROLE_CD, CHANGE_DATE, ENTRY_DATE, CHANGEBY_CHAR, STATUS_CD)
VALUES('<PROJECT_ID>','demo','EDITOR', now(), now(), null, 'A');